-- =============================================
-- INSERT SCHEMES DATA (145 schemes)
-- =============================================

INSERT INTO schemes (id, title, description, short_benefit, category, gender, min_age, max_age, category_eligible, income_limit, professions, student_levels, student_streams, education_percentage_min, employment_status, business_type, domicile_required, applicable_states, coverage, benefit_type, benefit_amount_min, benefit_amount_max, benefit_amount_text, required_documents, application_mode, official_url, helpline, department, ministry, source_verified_at, is_active, created_at, tags) VALUES
('ab5dbaa6-70b2-4f8e-bb48-f961bd971745', 'PM Suraksha Bima', 'Accident insurance at just 20 rupees per year', '2 lakh accidental death cover', 'general', NULL, 18, 70, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, ARRAY['All India'], 'All India', 'insurance', NULL, NULL, '2 lakh for accidental death', ARRAY['Aadhaar','Bank Account'], ARRAY['bank_branch'], 'https://jansuraksha.gov.in', NULL, 'Insurance Division', 'Ministry of Finance', NULL, true, '2026-07-15T13:10:51.711Z', ARRAY['insurance','accident']),
('874ed886-c05f-4584-8e62-d8af1e9740ce', 'PM Jeevan Jyoti Bima', 'Life insurance at just 436 rupees per year', '2 lakh life cover at 436/year', 'general', NULL, 18, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, ARRAY['All India'], 'All India', 'insurance', NULL, NULL, '2 lakh life cover', ARRAY['Aadhaar','Bank Account','Nomination'], ARRAY['bank_branch'], 'https://jansuraksha.gov.in', NULL, 'Insurance Division', 'Ministry of Finance', NULL, true, '2026-07-15T13:11:12.452Z', ARRAY['life insurance']),
('885546ba-7a5c-4b19-9a4d-22953298b5ed', 'Atal Pension Yojana', 'Pension scheme with Government co-contribution', '1000 to 5000 monthly pension', 'general', NULL, 18, 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, ARRAY['All India'], 'All India', 'pension', NULL, NULL, '1000 to 5000 monthly pension', ARRAY['Aadhaar','Bank Account'], ARRAY['bank_branch'], 'https://jeevanpramaan.gov.in', NULL, 'PFRDA', 'Ministry of Finance', NULL, true, '2026-07-15T13:11:12.452Z', ARRAY['pension','apry']),
('5aacee73-a5b2-4c2f-ac96-33f04edc37f8', 'PM SVANidhi', 'Micro credit for street vendors with interest subsidy', '50000 working capital loan', 'business', NULL, 18, NULL, NULL, NULL, ARRAY['vendor'], NULL, NULL, NULL, NULL, NULL, true, ARRAY['All India'], 'Urban', 'loan', NULL, NULL, '50000 + 7% interest subsidy', ARRAY['Aadhaar','Bank Account','Vendor Certificate'], ARRAY['bank'], 'https://pmsvanidhi.mca.gov.in', NULL, 'MoHUA', 'Ministry of Housing & Urban Affairs', NULL, true, '2026-07-15T13:11:12.452Z', ARRAY['vendor','loan']),
('c7f487fa-a00b-4c8e-ab90-a95991afc0a7', 'National Health Mission', 'Free healthcare at government hospitals', 'Free treatment at govt hospitals', 'health', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, ARRAY['All India'], 'All India', 'healthcare', NULL, NULL, 'Free medicine + treatment', ARRAY['Aadhaar','Ration Card'], ARRAY['government_hospital'], 'https://nhm.gov.in', NULL, 'NHSRC', 'Ministry of Health & FW', NULL, true, '2026-07-15T13:11:12.452Z', ARRAY['health','free']);
